p\_8105\_hw1\_ep2899
================

## Problem 2

## Load tidyverse

``` r
library(tidyverse)
```

    ## -- Attaching packages ------------------------------------------------------------------------ tidyverse 1.3.0 --

    ## v ggplot2 3.3.2     v purrr   0.3.4
    ## v tibble  3.0.3     v dplyr   1.0.2
    ## v tidyr   1.1.2     v stringr 1.4.0
    ## v readr   1.3.1     v forcats 0.5.0

    ## -- Conflicts --------------------------------------------------------------------------- tidyverse_conflicts() --
    ## x dplyr::filter() masks stats::filter()
    ## x dplyr::lag()    masks stats::lag()

## Read CSV

``` r
nyctransit_data = read_csv("./data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv")
```

    ## Parsed with column specification:
    ## cols(
    ##   .default = col_character(),
    ##   `Station Latitude` = col_double(),
    ##   `Station Longitude` = col_double(),
    ##   Route8 = col_double(),
    ##   Route9 = col_double(),
    ##   Route10 = col_double(),
    ##   Route11 = col_double(),
    ##   ADA = col_logical(),
    ##   `Free Crossover` = col_logical(),
    ##   `Entrance Latitude` = col_double(),
    ##   `Entrance Longitude` = col_double()
    ## )

    ## See spec(...) for full column specifications.

``` r
nyctransit_data = janitor::clean_names(nyctransit_data)
```

\#\#clean data

``` r
data_clean= select(nyctransit_data, -division, -staffing, -staff_hours, -ada_notes, -free_crossover, -north_south_street, -east_west_street, -corner, -entrance_latitude, -entrance_longitude, -station_location, -entrance_location) 
data_clean
```

    ## # A tibble: 1,868 x 20
    ##    line  station_name station_latitude station_longitu~ route1 route2 route3
    ##    <chr> <chr>                   <dbl>            <dbl> <chr>  <chr>  <chr> 
    ##  1 4 Av~ 25th St                  40.7            -74.0 R      <NA>   <NA>  
    ##  2 4 Av~ 25th St                  40.7            -74.0 R      <NA>   <NA>  
    ##  3 4 Av~ 36th St                  40.7            -74.0 N      R      <NA>  
    ##  4 4 Av~ 36th St                  40.7            -74.0 N      R      <NA>  
    ##  5 4 Av~ 36th St                  40.7            -74.0 N      R      <NA>  
    ##  6 4 Av~ 45th St                  40.6            -74.0 R      <NA>   <NA>  
    ##  7 4 Av~ 45th St                  40.6            -74.0 R      <NA>   <NA>  
    ##  8 4 Av~ 45th St                  40.6            -74.0 R      <NA>   <NA>  
    ##  9 4 Av~ 45th St                  40.6            -74.0 R      <NA>   <NA>  
    ## 10 4 Av~ 53rd St                  40.6            -74.0 R      <NA>   <NA>  
    ## # ... with 1,858 more rows, and 13 more variables: route4 <chr>, route5 <chr>,
    ## #   route6 <chr>, route7 <chr>, route8 <dbl>, route9 <dbl>, route10 <dbl>,
    ## #   route11 <dbl>, entrance_type <chr>, entry <chr>, exit_only <chr>,
    ## #   vending <chr>, ada <lgl>

\#\#convert character to logical

``` r
data_clean= data_clean %>%  
mutate(entry=ifelse(entry=="YES", TRUE, FALSE))
```

## short paragraph

This is a csv file data of NYC transit info containing 1868 rows x 20
columns, with information regarding line, station name, station
latitude, station longitude, routes served, entry, vending, entrance
type, and ADA compliance This data is not yet tidy

\#\#distinct

``` r
data_clean %>% 
distinct(line, station_name)%>% 
count()
```

    ## # A tibble: 1 x 1
    ##       n
    ##   <int>
    ## 1   465

There are 465 distinct stations, by line and station\_name

\#\#filter

``` r
filter(data_clean, ada==TRUE) 
```

    ## # A tibble: 468 x 20
    ##    line  station_name station_latitude station_longitu~ route1 route2 route3
    ##    <chr> <chr>                   <dbl>            <dbl> <chr>  <chr>  <chr> 
    ##  1 4 Av~ Atlantic Av~             40.7            -74.0 B      Q      D     
    ##  2 4 Av~ DeKalb Av                40.7            -74.0 B      Q      R     
    ##  3 4 Av~ DeKalb Av                40.7            -74.0 B      Q      R     
    ##  4 4 Av~ DeKalb Av                40.7            -74.0 B      Q      R     
    ##  5 4 Av~ DeKalb Av                40.7            -74.0 B      Q      R     
    ##  6 4 Av~ DeKalb Av                40.7            -74.0 B      Q      R     
    ##  7 4 Av~ DeKalb Av                40.7            -74.0 B      Q      R     
    ##  8 4 Av~ Pacific St               40.7            -74.0 B      Q      D     
    ##  9 4 Av~ Pacific St               40.7            -74.0 B      Q      D     
    ## 10 42nd~ Grand Centr~             40.8            -74.0 GS     4      5     
    ## # ... with 458 more rows, and 13 more variables: route4 <chr>, route5 <chr>,
    ## #   route6 <chr>, route7 <chr>, route8 <dbl>, route9 <dbl>, route10 <dbl>,
    ## #   route11 <dbl>, entrance_type <chr>, entry <lgl>, exit_only <chr>,
    ## #   vending <chr>, ada <lgl>

There are 458 stations which are ADA compliant

``` r
data_clean= data_clean %>%  
mutate(vending=ifelse(vending=="YES", TRUE, FALSE))
```

``` r
select (data_clean, entrance_type, exit_only, entry, vending) %>%  
filter(vending==FALSE) %>% 
  filter(entry==TRUE)
```

    ## # A tibble: 69 x 4
    ##    entrance_type exit_only entry vending
    ##    <chr>         <chr>     <lgl> <lgl>  
    ##  1 Stair         <NA>      TRUE  FALSE  
    ##  2 Stair         <NA>      TRUE  FALSE  
    ##  3 Stair         <NA>      TRUE  FALSE  
    ##  4 Stair         <NA>      TRUE  FALSE  
    ##  5 Stair         <NA>      TRUE  FALSE  
    ##  6 Stair         <NA>      TRUE  FALSE  
    ##  7 Stair         <NA>      TRUE  FALSE  
    ##  8 Stair         <NA>      TRUE  FALSE  
    ##  9 Stair         <NA>      TRUE  FALSE  
    ## 10 Stair         <NA>      TRUE  FALSE  
    ## # ... with 59 more rows

69/1868 or 3.7% of station entrances and exits without vending allow
entrance
